### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by olaulau** [jaybosamiya/nautilus-interactive-typeahead-debian#4]
Hi ;
when compiling with the `fakeroot debian/rules binary` command, it runs all the test suite, which seems to fail due to the behaviour change. and it takes a long time.
is there a way to disable the tests ?
I also got this error while compiling nautilus 3.34.1 (even without your patches) : `5/17 nautilus                                FAIL     0.42 s (killed by signal 5 SIGTRAP)`
any idea ?

**Comment by jaybosamiya** [comment]
Not really sure. My guess is that on that version (or sometime in between), the `debian/rules` file was updated to also run tests. It is just a standard makefile, so you should be able to read through it and try to figure out which of the rules goes over to the tests. Otherwise, I would suggest contacting the actual nautilus devs, or the main package maintainers to figure this out.
